name = "formulario-vander"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "example.com/*", zone_name = "example.com" }
]

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.jsx"]

[build.upload]
format = "service-worker"

[site]
bucket = "./dist"
