export const preSessionQuestions = [
  { id: 'email', label: 'E-mail', type: 'email', required: true },
  { id: 'name', label: 'Nome completo', type: 'text', required: true },
  { id: 'phone', label: 'Número para contato', type: 'tel', required: true },
  { id: 'age', label: 'Idade', type: 'number', required: true },
  { id: 'birthDate', label: 'Data de nascimento', type: 'date', required: true },
  { id: 'address', label: 'Endereço (CEP)', type: 'text', required: true },
  { id: 'religion', label: 'Religião', type: 'text', required: true },
  {
    id: 'maritalStatus',
    label: 'Estado civil',
    type: 'select',
    required: true,
    options: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'Prefiro não informar'],
  },
  { id: 'profession', label: 'Profissão', type: 'text', required: true },
  { id: 'income', label: 'Renda média', type: 'number', required: false },
  { id: 'therapyHistory', label: 'Já fez terapia? Se sim, por quanto tempo?', type: 'textarea', required: true },
  { id: 'diagnosis', label: 'Já recebeu algum diagnóstico?', type: 'textarea', required: true },
  { id: 'medication', label: 'Toma alguma medicação? Se sim, qual e em qual dosagem?', type: 'textarea', required: true },
  { id: 'routine', label: 'Como é a sua rotina?', type: 'textarea', required: true },
  { id: 'reason', label: 'O que te faz buscar terapia hoje?', type: 'textarea', required: true },
  {
    id: 'goals',
    label: 'O que você gostaria de concretizar dentro dos próximos três meses em terapia?',
    type: 'textarea',
    required: true,
  },
  { id: 'additional', label: 'Há mais algo que você julgue importante eu saber?', type: 'textarea', required: true },
];

